import type { User, Restaurant, Table, MenuItem, Reservation, Review, TableSession, Order } from '@/types/database'

export const MOCK_USERS: User[] = [
  {
    id: 'user-admin-1',
    name: 'Admin DineFirst',
    email: 'admin@dinefirst.com',
    role: 'admin',
    phone: '+34 600 000 001',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-rest-1',
    name: 'Carlos Mendoza',
    email: 'restaurante@demo.com',
    role: 'restaurante',
    phone: '+34 600 111 222',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'user-com-1',
    name: 'María García',
    email: 'comensal@demo.com',
    role: 'comensal',
    phone: '+34 600 333 444',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'user-com-2',
    name: 'Javier López',
    email: 'javier@demo.com',
    role: 'comensal',
    phone: '+34 600 555 666',
    createdAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'user-cam-1',
    name: 'Elena Ruiz',
    email: '',
    username: 'elena',
    role: 'camarero',
    phone: '+34 600 777 888',
    createdAt: '2026-03-01T00:00:00Z',
    restaurantId: 'rest-1',
  },
  {
    id: 'user-cam-2',
    name: 'Diego Torres',
    email: '',
    username: 'diego',
    role: 'camarero',
    phone: '+34 600 999 000',
    createdAt: '2026-03-05T00:00:00Z',
    restaurantId: 'rest-1',
  },
]

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    ownerId: 'user-rest-1',
    name: 'La Taberna del Chef',
    slug: 'la-taberna-del-chef',
    city: 'madrid',
    address: 'Calle Serrano 45, Madrid',
    cuisineType: 'Española Contemporánea',
    capacity: 60,
    description:
      'Un oasis gastronómico en el corazón de Madrid. Cocina española de autor con productos de temporada, vinos de pequeño productor y un ambiente íntimo que invita a quedarse. Cada plato es un homenaje a la tradición con toques de vanguardia.',
    plan: 'pro',
    isActive: true,
    rating: 4.7,
    reviewCount: 234,
    phone: '+34 91 555 12 34',
    openingHours: 'Mar–Dom 13:00–16:00, 20:00–24:00',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'rest-2',
    ownerId: 'user-rest-2',
    name: 'El Rincón de la Abuela',
    slug: 'el-rincon-de-la-abuela',
    city: 'barcelona',
    address: 'Carrer de Provença 82, Barcelona',
    cuisineType: 'Catalana Tradicional',
    capacity: 45,
    description:
      'Cuatro generaciones de cocina catalana auténtica. Los ingredientes llegan cada mañana del mercado de la Boqueria. El pa amb tomàquet, las croquetas de jamón ibérico y el crema catalana de temporada son irresistibles.',
    plan: 'basic',
    isActive: true,
    rating: 4.9,
    reviewCount: 512,
    phone: '+34 93 444 56 78',
    openingHours: 'Lun–Dom 12:00–16:00, 19:30–23:30',
    createdAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'rest-3',
    ownerId: 'user-rest-3',
    name: 'Sake & Fusion',
    slug: 'sake-and-fusion',
    city: 'madrid',
    address: 'Calle Fuencarral 120, Madrid',
    cuisineType: 'Japonesa Fusión',
    capacity: 35,
    description:
      'Donde el umami japonés se encuentra con la despensa mediterránea. Omakase dinámico, rolls de temporada y una carta de sakes cuidadosamente seleccionados. Para los amantes de la cocina japonesa y la aventura culinaria.',
    plan: 'premium',
    isActive: true,
    rating: 4.5,
    reviewCount: 178,
    phone: '+34 91 777 89 01',
    openingHours: 'Mié–Dom 13:30–15:30, 20:30–23:00',
    createdAt: '2026-02-01T00:00:00Z',
  },
]

export const MOCK_TABLES: Table[] = [
  // La Taberna del Chef
  { id: 't1-1', restaurantId: 'rest-1', name: 'Mesa 1', capacity: 2, status: 'occupied', location: 'Terraza', qrCode: 'df-rest1-t1' },
  { id: 't1-2', restaurantId: 'rest-1', name: 'Mesa 2', capacity: 4, status: 'free', location: 'Interior', qrCode: 'df-rest1-t2' },
  { id: 't1-3', restaurantId: 'rest-1', name: 'Mesa 3', capacity: 4, status: 'occupied', location: 'Interior', qrCode: 'df-rest1-t3' },
  { id: 't1-4', restaurantId: 'rest-1', name: 'Mesa 4', capacity: 6, status: 'reserved', location: 'Privado', qrCode: 'df-rest1-t4' },
  { id: 't1-5', restaurantId: 'rest-1', name: 'Mesa 5', capacity: 2, status: 'inactive', location: 'Barra', qrCode: 'df-rest1-t5' },
  { id: 't1-6', restaurantId: 'rest-1', name: 'Mesa 6', capacity: 8, status: 'free', location: 'Privado', qrCode: 'df-rest1-t6' },
  // El Rincón de la Abuela
  { id: 't2-1', restaurantId: 'rest-2', name: 'Mesa A', capacity: 2, status: 'free', location: 'Patio', qrCode: 'df-rest2-tA' },
  { id: 't2-2', restaurantId: 'rest-2', name: 'Mesa B', capacity: 4, status: 'en_route', location: 'Sala principal', qrCode: 'df-rest2-tB' },
  { id: 't2-3', restaurantId: 'rest-2', name: 'Mesa C', capacity: 4, status: 'free', location: 'Sala principal', qrCode: 'df-rest2-tC' },
  { id: 't2-4', restaurantId: 'rest-2', name: 'Mesa D', capacity: 6, status: 'occupied', location: 'Sala principal', qrCode: 'df-rest2-tD' },
  // Sake & Fusion
  { id: 't3-1', restaurantId: 'rest-3', name: 'Barra 1', capacity: 2, status: 'occupied', location: 'Barra omakase', qrCode: 'df-rest3-t1' },
  { id: 't3-2', restaurantId: 'rest-3', name: 'Barra 2', capacity: 2, status: 'free', location: 'Barra omakase', qrCode: 'df-rest3-t2' },
  { id: 't3-3', restaurantId: 'rest-3', name: 'Mesa 1', capacity: 4, status: 'free', location: 'Sala', qrCode: 'df-rest3-t3' },
  { id: 't3-4', restaurantId: 'rest-3', name: 'Mesa 2', capacity: 4, status: 'reserved', location: 'Sala', qrCode: 'df-rest3-t4' },
]

export const MOCK_SESSIONS: TableSession[] = [
  {
    id: 'sess-1',
    tableId: 't1-1',
    restaurantId: 'rest-1',
    startedAt: '2026-03-15T13:15:00Z',
    closedAt: null,
    totalAmount: 47,
  },
  {
    id: 'sess-2',
    tableId: 't1-3',
    restaurantId: 'rest-1',
    startedAt: '2026-03-15T14:00:00Z',
    closedAt: null,
    totalAmount: 62,
  },
  {
    id: 'sess-3',
    tableId: 't2-4',
    restaurantId: 'rest-2',
    startedAt: '2026-03-15T13:30:00Z',
    closedAt: null,
    totalAmount: 48,
  },
  {
    id: 'sess-4',
    tableId: 't3-1',
    restaurantId: 'rest-3',
    startedAt: '2026-03-15T20:45:00Z',
    closedAt: null,
    totalAmount: 57,
  },
  // ─── Sesiones históricas cerradas (rest-1) ──────────────────────────
  { id: 'sess-h1', tableId: 't1-2', restaurantId: 'rest-1', startedAt: '2026-03-14T13:00:00Z', closedAt: '2026-03-14T15:10:00Z', totalAmount: 90 },
  { id: 'sess-h2', tableId: 't1-6', restaurantId: 'rest-1', startedAt: '2026-03-14T20:00:00Z', closedAt: '2026-03-14T22:30:00Z', totalAmount: 62 },
  { id: 'sess-h3', tableId: 't1-1', restaurantId: 'rest-1', startedAt: '2026-03-13T12:30:00Z', closedAt: '2026-03-13T14:45:00Z', totalAmount: 48 },
  { id: 'sess-h4', tableId: 't1-3', restaurantId: 'rest-1', startedAt: '2026-03-12T20:00:00Z', closedAt: '2026-03-12T22:15:00Z', totalAmount: 92 },
  { id: 'sess-h5', tableId: 't1-2', restaurantId: 'rest-1', startedAt: '2026-03-11T13:00:00Z', closedAt: '2026-03-11T15:00:00Z', totalAmount: 44 },
  { id: 'sess-h6', tableId: 't1-6', restaurantId: 'rest-1', startedAt: '2026-03-10T19:30:00Z', closedAt: '2026-03-10T22:00:00Z', totalAmount: 108 },
  { id: 'sess-h7', tableId: 't1-1', restaurantId: 'rest-1', startedAt: '2026-03-09T12:00:00Z', closedAt: '2026-03-09T14:15:00Z', totalAmount: 64 },
  { id: 'sess-h8', tableId: 't1-4', restaurantId: 'rest-1', startedAt: '2026-03-08T20:00:00Z', closedAt: '2026-03-08T22:45:00Z', totalAmount: 78 },
]

export const MOCK_ORDERS: Order[] = [
  // Mesa 1 rest-1 — sesión sess-1
  {
    id: 'ord-1',
    sessionId: 'sess-1',
    tableId: 't1-1',
    restaurantId: 'rest-1',
    status: 'served',
    notes: '',
    createdAt: '2026-03-15T13:20:00Z',
    items: [
      { id: 'oi-1', orderId: 'ord-1', menuItemId: 'm1-1', name: 'Croquetas de jamón ibérico', price: 12, quantity: 1, notes: '' },
      { id: 'oi-2', orderId: 'ord-1', menuItemId: 'm1-2', name: 'Gazpacho de temporada', price: 9, quantity: 1, notes: 'Sin cebolla' },
    ],
  },
  {
    id: 'ord-2',
    sessionId: 'sess-1',
    tableId: 't1-1',
    restaurantId: 'rest-1',
    status: 'preparing',
    notes: '',
    createdAt: '2026-03-15T13:45:00Z',
    items: [
      { id: 'oi-3', orderId: 'ord-2', menuItemId: 'm1-5', name: 'Lubina a la sal', price: 28, quantity: 1, notes: '' },
    ],
  },
  // Mesa 3 rest-1 — sesión sess-2
  {
    id: 'ord-3',
    sessionId: 'sess-2',
    tableId: 't1-3',
    restaurantId: 'rest-1',
    status: 'pending',
    notes: 'Alérgicos a marisco',
    createdAt: '2026-03-15T14:05:00Z',
    items: [
      { id: 'oi-4', orderId: 'ord-3', menuItemId: 'm1-3', name: 'Steak tartar', price: 18, quantity: 2, notes: '' },
      { id: 'oi-5', orderId: 'ord-3', menuItemId: 'm1-4', name: 'Cocido madrileño', price: 24, quantity: 1, notes: '' },
      { id: 'oi-6', orderId: 'ord-3', menuItemId: 'm1-9', name: 'Agua mineral', price: 3, quantity: 2, notes: 'Con gas' },
    ],
  },
  // Mesa D rest-2 — sesión sess-3
  {
    id: 'ord-4',
    sessionId: 'sess-3',
    tableId: 't2-4',
    restaurantId: 'rest-2',
    status: 'served',
    notes: '',
    createdAt: '2026-03-15T13:35:00Z',
    items: [
      { id: 'oi-7', orderId: 'ord-4', menuItemId: 'm2-1', name: 'Pa amb tomàquet', price: 4, quantity: 3, notes: '' },
      { id: 'oi-8', orderId: 'ord-4', menuItemId: 'm2-3', name: 'Fideuà de gambas y sepia', price: 22, quantity: 2, notes: '' },
    ],
  },
  // Barra 1 rest-3 — sesión sess-4
  {
    id: 'ord-5',
    sessionId: 'sess-4',
    tableId: 't3-1',
    restaurantId: 'rest-3',
    status: 'preparing',
    notes: '',
    createdAt: '2026-03-15T20:50:00Z',
    items: [
      { id: 'oi-9', orderId: 'ord-5', menuItemId: 'm3-4', name: 'Omakase del chef (8 piezas)', price: 45, quantity: 1, notes: '' },
      { id: 'oi-10', orderId: 'ord-5', menuItemId: 'm3-7', name: 'Sake Junmai Daiginjo (copa)', price: 12, quantity: 1, notes: '' },
    ],
  },
  // ─── Órdenes históricas rest-1 (para analytics) ─────────────────────────────
  {
    id: 'ord-h1', sessionId: 'sess-h1', tableId: 't1-2', restaurantId: 'rest-1', status: 'paid', notes: '', createdAt: '2026-03-14T14:10:00Z',
    items: [
      { id: 'oi-h1', orderId: 'ord-h1', menuItemId: 'm1-1', name: 'Croquetas de jamón ibérico', price: 12, quantity: 2, notes: '' },
      { id: 'oi-h2', orderId: 'ord-h1', menuItemId: 'm1-4', name: 'Cocido madrileño', price: 24, quantity: 2, notes: '' },
      { id: 'oi-h3', orderId: 'ord-h1', menuItemId: 'm1-8', name: 'Vino de la casa (copa)', price: 6, quantity: 3, notes: '' },
    ],
  },
  {
    id: 'ord-h2', sessionId: 'sess-h2', tableId: 't1-6', restaurantId: 'rest-1', status: 'paid', notes: '', createdAt: '2026-03-14T21:20:00Z',
    items: [
      { id: 'oi-h4', orderId: 'ord-h2', menuItemId: 'm1-3', name: 'Steak tartar', price: 18, quantity: 1, notes: '' },
      { id: 'oi-h5', orderId: 'ord-h2', menuItemId: 'm1-5', name: 'Lubina a la sal', price: 28, quantity: 1, notes: '' },
      { id: 'oi-h6', orderId: 'ord-h2', menuItemId: 'm1-7', name: 'Torrija caramelizada', price: 8, quantity: 2, notes: '' },
    ],
  },
  {
    id: 'ord-h3', sessionId: 'sess-h3', tableId: 't1-1', restaurantId: 'rest-1', status: 'paid', notes: '', createdAt: '2026-03-13T13:45:00Z',
    items: [
      { id: 'oi-h7', orderId: 'ord-h3', menuItemId: 'm1-2', name: 'Gazpacho de temporada', price: 9, quantity: 2, notes: '' },
      { id: 'oi-h8', orderId: 'ord-h3', menuItemId: 'm1-4', name: 'Cocido madrileño', price: 24, quantity: 1, notes: '' },
      { id: 'oi-h9', orderId: 'ord-h3', menuItemId: 'm1-9', name: 'Agua mineral', price: 3, quantity: 2, notes: '' },
    ],
  },
  {
    id: 'ord-h4', sessionId: 'sess-h4', tableId: 't1-3', restaurantId: 'rest-1', status: 'paid', notes: '', createdAt: '2026-03-12T21:00:00Z',
    items: [
      { id: 'oi-h10', orderId: 'ord-h4', menuItemId: 'm1-1', name: 'Croquetas de jamón ibérico', price: 12, quantity: 1, notes: '' },
      { id: 'oi-h11', orderId: 'ord-h4', menuItemId: 'm1-5', name: 'Lubina a la sal', price: 28, quantity: 2, notes: '' },
      { id: 'oi-h12', orderId: 'ord-h4', menuItemId: 'm1-8', name: 'Vino de la casa (copa)', price: 6, quantity: 4, notes: '' },
    ],
  },
  {
    id: 'ord-h5', sessionId: 'sess-h5', tableId: 't1-2', restaurantId: 'rest-1', status: 'paid', notes: '', createdAt: '2026-03-11T14:30:00Z',
    items: [
      { id: 'oi-h13', orderId: 'ord-h5', menuItemId: 'm1-3', name: 'Steak tartar', price: 18, quantity: 2, notes: '' },
      { id: 'oi-h14', orderId: 'ord-h5', menuItemId: 'm1-7', name: 'Torrija caramelizada', price: 8, quantity: 1, notes: '' },
    ],
  },
  {
    id: 'ord-h6', sessionId: 'sess-h6', tableId: 't1-6', restaurantId: 'rest-1', status: 'paid', notes: '', createdAt: '2026-03-10T20:45:00Z',
    items: [
      { id: 'oi-h15', orderId: 'ord-h6', menuItemId: 'm1-4', name: 'Cocido madrileño', price: 24, quantity: 3, notes: '' },
      { id: 'oi-h16', orderId: 'ord-h6', menuItemId: 'm1-2', name: 'Gazpacho de temporada', price: 9, quantity: 3, notes: '' },
      { id: 'oi-h17', orderId: 'ord-h6', menuItemId: 'm1-9', name: 'Agua mineral', price: 3, quantity: 3, notes: '' },
    ],
  },
  {
    id: 'ord-h7', sessionId: 'sess-h7', tableId: 't1-1', restaurantId: 'rest-1', status: 'paid', notes: '', createdAt: '2026-03-09T13:15:00Z',
    items: [
      { id: 'oi-h18', orderId: 'ord-h7', menuItemId: 'm1-1', name: 'Croquetas de jamón ibérico', price: 12, quantity: 3, notes: '' },
      { id: 'oi-h19', orderId: 'ord-h7', menuItemId: 'm1-5', name: 'Lubina a la sal', price: 28, quantity: 1, notes: '' },
    ],
  },
  {
    id: 'ord-h8', sessionId: 'sess-h8', tableId: 't1-4', restaurantId: 'rest-1', status: 'paid', notes: '', createdAt: '2026-03-08T21:30:00Z',
    items: [
      { id: 'oi-h20', orderId: 'ord-h8', menuItemId: 'm1-3', name: 'Steak tartar', price: 18, quantity: 1, notes: '' },
      { id: 'oi-h21', orderId: 'ord-h8', menuItemId: 'm1-4', name: 'Cocido madrileño', price: 24, quantity: 1, notes: '' },
      { id: 'oi-h22', orderId: 'ord-h8', menuItemId: 'm1-7', name: 'Torrija caramelizada', price: 8, quantity: 3, notes: '' },
      { id: 'oi-h23', orderId: 'ord-h8', menuItemId: 'm1-8', name: 'Vino de la casa (copa)', price: 6, quantity: 2, notes: '' },
    ],
  },
]

export const MOCK_MENU_ITEMS: MenuItem[] = [
  // La Taberna del Chef
  { id: 'm1-1', restaurantId: 'rest-1', name: 'Croquetas de jamón ibérico', description: 'Bechamel cremosa, jamón ibérico DO, panko dorado', price: 12, category: 'entrantes', isAvailable: true, imageUrl: 'https://images.unsplash.com/photo-1554433607-66b5efe9d304?w=400&h=300&fit=crop' },
  { id: 'm1-2', restaurantId: 'rest-1', name: 'Gazpacho de temporada', description: 'Tomates de huerta, pepino, pimiento y aceite virgen extra', price: 9, category: 'entrantes', isAvailable: true, imageUrl: 'https://images.unsplash.com/photo-1600335895229-6e75511892c8?w=400&h=300&fit=crop' },
  { id: 'm1-3', restaurantId: 'rest-1', name: 'Steak tartar', description: 'Solomillo picado a cuchillo, alcaparras, mostaza Dijon, yema curada', price: 18, category: 'entrantes', isAvailable: true, imageUrl: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=400&h=300&fit=crop' },
  { id: 'm1-4', restaurantId: 'rest-1', name: 'Cocido madrileño', description: 'Receta tradicional de tres vuelcos, garbanzos de Fuentesaúco', price: 24, category: 'principales', isAvailable: true, imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop' },
  { id: 'm1-5', restaurantId: 'rest-1', name: 'Lubina a la sal', description: 'Lubina salvaje, sal marina, aceite de oliva arbequina, limón', price: 28, category: 'principales', isAvailable: true, imageUrl: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=400&h=300&fit=crop' },
  { id: 'm1-6', restaurantId: 'rest-1', name: 'Entrecot de vaca madurada', description: '400g, maduración 45 días, chimichurri casero, patatas paja', price: 34, category: 'principales', isAvailable: false, imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=300&fit=crop' },
  { id: 'm1-7', restaurantId: 'rest-1', name: 'Torrija caramelizada', description: 'Pan brioche, crema de vainilla, helado de azafrán', price: 8, category: 'postres', isAvailable: true, imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&h=300&fit=crop' },
  { id: 'm1-8', restaurantId: 'rest-1', name: 'Vino de la casa (copa)', description: 'Selección del sumiller, rota cada semana', price: 6, category: 'bebidas', isAvailable: true, imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop' },
  { id: 'm1-9', restaurantId: 'rest-1', name: 'Agua mineral', description: 'Botella 1L con o sin gas', price: 3, category: 'bebidas', isAvailable: true, imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400&h=300&fit=crop' },

  // El Rincón de la Abuela
  { id: 'm2-1', restaurantId: 'rest-2', name: 'Pa amb tomàquet', description: 'Pan artesano, tomate restregado, aceite virgen extra, sal gruesa', price: 4, category: 'entrantes', isAvailable: true },
  { id: 'm2-2', restaurantId: 'rest-2', name: 'Esqueixada de bacallà', description: 'Bacalao desalado, tomate, aceitunas negras, cebolla tierna', price: 14, category: 'entrantes', isAvailable: true },
  { id: 'm2-3', restaurantId: 'rest-2', name: 'Fideuà de gambas y sepia', description: 'Fideos rossejats, gambas rojas, sepia, all i oli casero', price: 22, category: 'principales', isAvailable: true },
  { id: 'm2-4', restaurantId: 'rest-2', name: "Escudella i carn d'olla", description: 'Cocido catalán tradicional, pilota, butifarras, verduras', price: 20, category: 'principales', isAvailable: true },
  { id: 'm2-5', restaurantId: 'rest-2', name: 'Crema catalana', description: 'Receta de la abuela, azúcar caramelizado al momento', price: 7, category: 'postres', isAvailable: true },
  { id: 'm2-6', restaurantId: 'rest-2', name: 'Mel i mató', description: 'Queso fresco artesano, miel de romero, nueces', price: 6, category: 'postres', isAvailable: true },
  { id: 'm2-7', restaurantId: 'rest-2', name: 'Cava (botella)', description: 'Cava brut nature DO Penedès, botella 75cl', price: 22, category: 'bebidas', isAvailable: true },

  // Sake & Fusion
  { id: 'm3-1', restaurantId: 'rest-3', name: 'Edamame con flor de sal', description: 'Edamame al vapor, flor de sal de Ibiza', price: 6, category: 'entrantes', isAvailable: true },
  { id: 'm3-2', restaurantId: 'rest-3', name: 'Gyoza de cerdo ibérico', description: '6 piezas, cerdo ibérico, cebollino, soja ponzu', price: 12, category: 'entrantes', isAvailable: true },
  { id: 'm3-3', restaurantId: 'rest-3', name: 'Tartar de atún rojo', description: 'Atún rojo del Mediterráneo, aguacate, tobiko, trufa', price: 22, category: 'entrantes', isAvailable: true },
  { id: 'm3-4', restaurantId: 'rest-3', name: 'Omakase del chef (8 piezas)', description: 'Selección del chef según mercado: 4 nigiri + 2 sashimi + 2 rolls', price: 45, category: 'principales', isAvailable: true },
  { id: 'm3-5', restaurantId: 'rest-3', name: 'Ramen tonkotsu ibérico', description: 'Caldo 18h, cerdo ibérico, huevo ajitsuke, alga nori, bambú', price: 18, category: 'principales', isAvailable: true },
  { id: 'm3-6', restaurantId: 'rest-3', name: 'Mochi de té matcha', description: 'Mochi casero, helado de matcha premium, salsa de sésamo', price: 8, category: 'postres', isAvailable: true },
  { id: 'm3-7', restaurantId: 'rest-3', name: 'Sake Junmai Daiginjo (copa)', description: 'Selección premium, copa 90ml, servido frío', price: 12, category: 'bebidas', isAvailable: true },
]

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'res-1',
    userId: 'user-com-1',
    userName: 'María García',
    userEmail: 'comensal@demo.com',
    userPhone: '+34 600 333 444',
    restaurantId: 'rest-1',
    restaurantName: 'La Taberna del Chef',
    restaurantCity: 'madrid',
    tableId: 't1-2',
    tableName: 'Mesa 2',
    date: '2026-03-15',
    time: '21:00',
    partySize: 2,
    status: 'confirmed',
    specialRequests: 'Alérgica a los frutos secos',
    confirmationCode: 'DF-A1B2C3',
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'res-2',
    userId: 'user-com-1',
    userName: 'María García',
    userEmail: 'comensal@demo.com',
    userPhone: '+34 600 333 444',
    restaurantId: 'rest-3',
    restaurantName: 'Sake & Fusion',
    restaurantCity: 'madrid',
    tableId: 't3-3',
    tableName: 'Mesa 1',
    date: '2026-03-20',
    time: '20:30',
    partySize: 4,
    status: 'pending',
    specialRequests: '',
    confirmationCode: 'DF-D4E5F6',
    createdAt: '2026-03-11T09:00:00Z',
  },
  {
    id: 'res-3',
    userId: 'user-com-2',
    userName: 'Javier López',
    userEmail: 'javier@demo.com',
    userPhone: '+34 600 555 666',
    restaurantId: 'rest-1',
    restaurantName: 'La Taberna del Chef',
    restaurantCity: 'madrid',
    tableId: 't1-4',
    tableName: 'Mesa 4',
    date: '2026-03-12',
    time: '14:00',
    partySize: 6,
    status: 'confirmed',
    specialRequests: 'Cumpleaños, necesitamos mesa especial',
    confirmationCode: 'DF-G7H8I9',
    createdAt: '2026-03-09T18:00:00Z',
  },
  {
    id: 'res-4',
    userId: 'user-com-1',
    userName: 'María García',
    userEmail: 'comensal@demo.com',
    userPhone: '+34 600 333 444',
    restaurantId: 'rest-2',
    restaurantName: 'El Rincón de la Abuela',
    restaurantCity: 'barcelona',
    tableId: 't2-2',
    tableName: 'Mesa B',
    date: '2026-02-28',
    time: '13:30',
    partySize: 3,
    status: 'cancelled',
    specialRequests: '',
    confirmationCode: 'DF-J0K1L2',
    createdAt: '2026-02-20T12:00:00Z',
  },
  {
    id: 'res-5',
    userId: 'user-com-2',
    userName: 'Javier López',
    userEmail: 'javier@demo.com',
    userPhone: '+34 600 555 666',
    restaurantId: 'rest-1',
    restaurantName: 'La Taberna del Chef',
    restaurantCity: 'madrid',
    tableId: 't1-3',
    tableName: 'Mesa 3',
    date: '2026-03-18',
    time: '21:30',
    partySize: 4,
    status: 'pending',
    specialRequests: 'Preferimos mesa junto a la ventana',
    confirmationCode: 'DF-M3N4O5',
    createdAt: '2026-03-11T14:00:00Z',
  },
]

export const MOCK_REVIEWS: Review[] = [
  // La Taberna del Chef (rest-1) — rating ~4.7
  { id: 'rev-1', restaurantId: 'rest-1', userId: 'user-com-1', userName: 'María García', rating: 5, comment: 'Las croquetas de jamón ibérico son las mejores que he probado en Madrid. Ambiente íntimo y servicio impecable. Volveremos seguro.', createdAt: '2026-03-01T12:00:00Z', response: 'Muchas gracias María! Nos alegra que disfrutaras de las croquetas, son nuestro orgullo. Te esperamos pronto!', respondedAt: '2026-03-02T10:00:00Z', verified: true, reservationId: 'res-1' },
  { id: 'rev-2', restaurantId: 'rest-1', userId: 'user-com-2', userName: 'Javier López', rating: 5, comment: 'El cocido madrileño de tres vuelcos es espectacular. Productos de primera calidad y una presentación muy cuidada.', createdAt: '2026-02-25T19:00:00Z', response: 'Gracias Javier! El cocido es nuestro plato estrella. Usamos garbanzos de Fuentesaúco y productos de temporada.', respondedAt: '2026-02-26T11:00:00Z', verified: true, reservationId: 'res-2' },
  { id: 'rev-3', restaurantId: 'rest-1', userId: 'user-com-3', userName: 'Laura Martínez', rating: 4, comment: 'Muy buena cocina aunque la espera fue algo larga. La torrija caramelizada es un pecado delicioso.', createdAt: '2026-02-18T21:30:00Z', verified: false },
  { id: 'rev-4', restaurantId: 'rest-1', userId: 'user-com-4', userName: 'Pablo Ruiz', rating: 4, comment: 'Gran relación calidad-precio para el nivel de cocina que ofrecen. El steak tartar, perfecto.', createdAt: '2026-02-10T14:00:00Z', response: 'Apreciamos tu comentario Pablo. El steak tartar lo preparamos con solomillo cortado a cuchillo al momento!', respondedAt: '2026-02-12T09:00:00Z', verified: true, reservationId: 'res-4' },
  // El Rincón de la Abuela (rest-2) — rating ~4.9
  { id: 'rev-5', restaurantId: 'rest-2', userId: 'user-com-1', userName: 'María García', rating: 5, comment: 'La crema catalana de la abuela es legendaria. Cuatro generaciones de saber hacer se notan en cada plato.', createdAt: '2026-03-05T13:00:00Z', verified: true, reservationId: 'res-5' },
  { id: 'rev-6', restaurantId: 'rest-2', userId: 'user-com-2', userName: 'Javier López', rating: 5, comment: 'Fideuà de gambas increíble. El patio interior es un oasis en Barcelona. Reservad con antelación.', createdAt: '2026-02-28T20:00:00Z', verified: true, reservationId: 'res-6' },
  { id: 'rev-7', restaurantId: 'rest-2', userId: 'user-com-5', userName: 'Ana Torres', rating: 5, comment: 'Pa amb tomàquet y mel i mató para terminar. Sencillo pero perfecto. Autenticidad catalana en estado puro.', createdAt: '2026-02-20T12:30:00Z', verified: false },
  // Sake & Fusion (rest-3) — rating ~4.5
  { id: 'rev-8', restaurantId: 'rest-3', userId: 'user-com-1', userName: 'María García', rating: 5, comment: 'El omakase del chef es una experiencia única. Fusión japonesa-mediterránea muy bien ejecutada.', createdAt: '2026-03-08T21:00:00Z', verified: true, reservationId: 'res-7' },
  { id: 'rev-9', restaurantId: 'rest-3', userId: 'user-com-2', userName: 'Javier López', rating: 4, comment: 'Ramen tonkotsu con cerdo ibérico: una locura. El sake Junmai Daiginjo marida genial.', createdAt: '2026-03-02T20:30:00Z', verified: false },
  { id: 'rev-10', restaurantId: 'rest-3', userId: 'user-com-6', userName: 'Carlos Fernández', rating: 4, comment: 'Gyozas de cerdo ibérico muy originales. Solo abren de miércoles a domingo, tened cuidado.', createdAt: '2026-02-15T13:30:00Z', verified: false },
]
